name: Terraform Security Scan

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run tfsec
      uses: aquasecurity/tfsec-action@v1.0.0
      with:
        soft_fail: false

    - name: Run checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: .
        framework: terraform
        soft_fail: false
        check_severity_threshold: HIGH

    - name: Initialize Terraform
      run: terraform init -backend=false

    - name: Check Formatting
      run: terraform fmt -check -diff -recursive